# Site settings
title: Secret Whiteboard #Jekyll-Uno
description: "JHO's functional fitness/ crossfit training log" #'Jekyll-Uno - a minimal, responsive theme for Jekyll'
url: 'http://ohjho.github.io/jekyll-uno'
baseurl: '/jekyll-uno/'
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'secret-whiteboard'

author:
  name: 'John Ho'
  email: iam@johnho.ca
#  twitter_username: joshgerdes
#  facebook_username: joshgerdes
#  github_username:  joshgerdes
#  linkedin_username:  joshgerdes

social-icons:
  - title: Crossfit
    url: http://games.crossfit.com/athlete/100455
    class: crossfit

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge
future: true

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
